### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anikethsaha** [anikethsaha/postcss-lowercase-text#1]
### 1.  Unit transformation (done at v0.3.0)

```css
h1 {
  border: 10PX;
}
```

⬇️

```css
h1 {
  border: 10px;
}
```

### 2. refactoring the existing selector transformer using `postcss-selector-parser` (done at v0.4.0)
